### ISSUE TITLE
Feature request: support `pydantic` schema

### ISSUE THREAD

**Issue by kemingy** [flasgger/flasgger#327]
Recently I just found [fastapi](https://github.com/tiangolo/fastapi) has very nice OpenAPI support with the help of [pydantic](https://github.com/samuelcolvin/pydantic)(Python 3.6+). So people can declare schema with Python types, which is very convenient.

Would like to know if this library will support pydantic in the future? Or if there is something I can do to help?

**Comment by rochacbruno** [comment]
There was long time ago this `@definition` decorator, which took a `ClassBAsedSwaggerDefinition`

https://github.com/flasgger/flasgger/blob/1c6ecde38a005466374246fb84497fa21a07272b/flasgger/base.py#L475-L480

YOu registered class definitions usign that decorator like in

https://github.com/flasgger/flasgger/blob/6bdacbafd9aa84f6d6f319a5a84b6fb90cc2b5a6/examples/definition_object_test.py#L19-L51

and it would be read when generating api spec.

That functionality can be refactored to take `pydantic`  definitions instead of that bare class.

**Comment by kemingy** [comment]
Thanks for your help.

Currently, I'm working on the API part of Machine Learning Service. All of the Python code is 3.6+, so I write my own library [flaskerk](https://github.com/kemingy/flaskerk), which is simple but fits my need.

Really appreciate for your help.
